version: '3.8'
services:
  kvserver-c-cpp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: kvserver-c-cpp
    ports:
      - "8080:8080"
    command: ./server
    mem_limit: 512m
    cpus: 2

  kvserver-zig-cpp:
    build:
      context: .
      dockerfile: Dockerfile-zig
    image: kvserver-zig-cpp
    ports:
      - "8081:8080"
    command: ./server
    mem_limit: 512m
    cpus: 2

  kvserver-zig-rust:
    build:
      context: .
      dockerfile: Dockerfile-z-rs
    image: kvserver-zig-rust
    ports:
      - "8082:8080"
    command: ./server
    mem_limit: 512m
    cpus: 2

  kvserver-c-rust:
    build:
      context: .
      dockerfile: Dockerfile-rust
    image: kvserver-c-rust
    ports:
      - "8083:8080"
    command: ./server
    mem_limit: 512m
    cpus: 2
